Repository jqlang/jq, pull requests merged in 2023-09, with the labels that each got.

#2888 Disable core.autocrlf on Windows to prevent submodule diffs (fix #2886)
  .github/workflows/ci.yml
Labels: release/packaging, windows

#2899 Invalid checksum file
  .github/workflows/ci.yml
  sig/v1.7/sha256sum.txt
Labels: release/packaging

#2915 main.c: Remove unused EXIT_STATUS_EXACT option
  src/main.c
Labels: lint
