Repository jqlang/jq, pull requests merged in 2023-07, with the labels that each got.

#2620 Release pipeline
  .github/workflows/ci.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: release/packaging

#2647 Strip debug information from executables (fix #1221)
  .github/workflows/ci.yml
Labels: release/packaging

#2093 Fix the default search paths and documentation
  docs/content/manual/manual.yml
  docs/content/manual/v1.5/manual.yml
  docs/content/manual/v1.6/manual.yml
  src/main.c
Labels: bug, docs

#2645 manual.yml: fix references to javascript, and clarify semantics of ==
  docs/content/manual/manual.yml
  tests/man.test
Labels: docs

#2648 Create dist and upload on release also disable docs on build
  .github/workflows/ci.yml
  .github/workflows/scanbuild.yml
  .gitignore
  README.md
Labels: release/packaging

#1961 Implement scan/2 filter
  src/builtin.jq
  tests/onig.test
Labels: feature request

#2598 Support optional else-branch for if-then-elif-end
  docs/content/manual/manual.yml
  src/parser.c
  src/parser.y
  tests/jq.test
Labels: feature request

#2649 Improve Dockerfile: update base image and optimize image size
  .github/workflows/ci.yml
  Dockerfile
Labels: docker

#2651 Fix release workflow tag trigger pattern
  .github/workflows/ci.yml
Labels: release/packaging

#2642 Setup path correctly after stream parsing a key:value object pair
  src/jv_parse.c
  tests/shtest
Labels: bug

#2253 Make 0 divided by 0 results in NaN consistently
  src/builtin.c
  tests/jq.test
Labels: bug

#2652 Release Docker image to GitHub Container Registry
  .github/workflows/ci.yml
Labels: release/packaging, docker

#2653 Remove outdated CI badges from README.md
  README.md
Labels: docs

#2654 Fix exit code on JSON parse error
  src/main.c
  tests/shtest
Labels: bug

#2661 Fix dumping large floating numbers (fix #2367)
  src/jv.c
  tests/shtest
Labels: bug

#2142 Fix string multiplication with a value between 0.0 and 1.0
  src/builtin.c
  tests/jq.test
Labels: bug

#2673 Fix the latest manual on string multiplication by zero
  docs/content/manual/manual.yml
Labels: docs

#2674 Fix nth/2 to emit empty on index out of range
  docs/content/manual/manual.yml
  src/builtin.jq
  tests/jq.test
Labels: bug

#2678 Fix manual on paths/1 to use boolean filter for its argument
  docs/content/manual/manual.yml
  docs/content/manual/v1.5/manual.yml
  docs/content/manual/v1.6/manual.yml
  tests/man.test
Labels: docs

#2677 Fix empty regular expression matches (fix #2565)
  src/builtin.c
  tests/onig.test
Labels: bug

#2665 Cross compile for Linux, MacOS and Windows on CI
  .github/workflows/ci.yml
  src/jv.c
  src/jv_thread.h
Labels: release/packaging

#2686 Build Docker image using pre-built executables
  .github/workflows/ci.yml
Labels: release/packaging, docker

#2255 Added a first fuzzer for integration with OSS-Fuzz.
  tests/jq_fuzz_parse.c
Labels: security

#2715 Fix memory leak on halt_error/1
  src/main.c
Labels: bug

#2714 On linux amd64, run tests with valgrind
  .github/workflows/valgrind.yml
Labels: test

#2713 Fix autoreconf warnings
  configure.ac
  m4/ax_pthread.m4
Labels: build

#2720 Make stream parser error when a non-empty object or array is used as key
  src/jv_parse.c
  tests/shtest
Labels: bug

#2722 Split man.test to make tests pass without oniguruma
  .gitattributes
  .github/workflows/manpage.yml
  Makefile.am
  README.md
  configure.ac
  docs/README.md
  docs/build_mantests.py
  tests/man.test
  tests/manonig.test
  tests/manonigtest
  tests/mantest
Labels: test

#2723 Add oniguruma workflow to test regex options
  .github/workflows/oniguruma.yml
Labels: test, oniguruma

#2703 Make object key color configurable (close #1739, #1791, #2638)
  docs/content/manual/manual.yml
  jq.1.prebuilt
  src/jv_print.c
  tests/shtest
Labels: feature request

#2730 Enable valgrind in oniguruma workflow
  .github/workflows/oniguruma.yml
Labels: test

#2728 Respect NO_COLOR environment variable to disable color output
  src/main.c
  tests/shtest
Labels: feature request

#2735 manual.yml: revise section on identity, clarifying what might change
  docs/content/manual/manual.yml
  jq.1.prebuilt
  tests/man.test
Labels: docs

#2000 Fix assertion when using multiple data imports
  src/compile.c
Labels: bug

#2740 Clarify the Docker image location (close #1864)
  README.md
  docs/content/download/default.yml
Labels: docs, docker

#2737 manual.yml: some clarifications plus fixes for markdown bloopers
  docs/content/manual/manual.yml
  jq.1.prebuilt
Labels: docs

#2741 Remove AppVeyor configuration
  appveyor.yml
Labels: test

#2739 Fail quickly if not in git repository in scripts/version
  scripts/version
Labels: build

#2743 Enable verbose output of make check
  .github/workflows/ci.yml
  .github/workflows/oniguruma.yml
  .github/workflows/valgrind.yml
  Dockerfile
Labels: test

#2747 Improve --help to mention all the command options
  docs/content/manual/manual.yml
  docs/content/manual/v1.4/manual.yml
  docs/content/manual/v1.5/manual.yml
  docs/content/manual/v1.6/manual.yml
  jq.1.prebuilt
  src/main.c
Labels: docs

#2751 Fix stderr to output string with no decoration (fix #2063)
  src/builtin.c
  src/execute.c
  src/jq.h
  src/main.c
  tests/shtest
Labels: bug

#2744 Improve manual in various ways (inputs, sort_by, foreach sections, etc.)
  docs/content/download/default.yml
  docs/content/manual/manual.yml
  docs/content/manual/v1.3/manual.yml
  docs/content/manual/v1.4/manual.yml
  docs/content/manual/v1.5/manual.yml
  docs/content/manual/v1.6/manual.yml
  jq.1.prebuilt
  tests/jq.test
  tests/man.test
Labels: docs

#2758 builtin.jq: simpler and faster transpose
  src/builtin.jq
  tests/jq.test
Labels: performance

#2766 Reorder the command line options in the manual
  docs/content/manual/manual.yml
  docs/content/manual/v1.3/manual.yml
  docs/content/manual/v1.4/manual.yml
  docs/content/manual/v1.5/manual.yml
  docs/content/manual/v1.6/manual.yml
  jq.1.prebuilt
  src/main.c
Labels: docs

#2646 implode: Better invalid input validation and handling
  src/builtin.c
  src/jv.c
  src/jv.h
  src/jv_type_private.h
  tests/jq.test
Labels: bug

#2771 Make sure to free default @text format on error
  src/parser.c
  src/parser.y
Labels: bug

#2684 Rename --nul-output to --raw-output0, abort on string containing NUL
  docs/content/manual/manual.yml
  jq.1.prebuilt
  src/main.c
  tests/shtest
Labels: feature request

#2782 Fix memory leak for { $foo: bar }
  src/parser.c
  src/parser.y
  tests/jq.test
Labels: bug

#2599 Replace NEWS with NEWS.md with more details and examples
  NEWS
  NEWS.md
  docs/templates/shared/_navbar.html.j2
Labels: release/packaging

#2791 Fix typo in manual: "-seq" => "--seq"
  docs/content/manual/manual.yml
  docs/content/manual/v1.5/manual.yml
  docs/content/manual/v1.6/manual.yml
  jq.1.prebuilt
Labels: docs

#2628 Redesign website
  .github/workflows/website.yml
  Makefile.am
  docs/README.md
  docs/build_website.py
  docs/content/download/default.yml
  docs/content/index.yml
  docs/content/manual/manual.yml
  docs/content/manual/v1.3/manual.yml
  docs/content/manual/v1.4/manual.yml
  docs/content/manual/v1.5/manual.yml
  docs/content/manual/v1.6/manual.yml
  docs/public/css/base.css
  docs/public/css/base.scss
  docs/public/css/style.css
  docs/public/icon.png
  docs/public/icon.svg
  docs/public/jq.png
  docs/public/jq.svg
  docs/public/js/manual-search.js
  docs/site.yml
  docs/templates/default.html.j2
  docs/templates/index.html.j2
  docs/templates/manual.html.j2
  docs/templates/shared/_footer.html.j2
  docs/templates/shared/_head.html.j2
  docs/templates/shared/_navbar.html.j2
Labels: docs

#2797 Fix constant folding of division and reminder with zero divisor
  src/builtin.c
  src/compile.c
  src/compile.h
  src/parser.c
  src/parser.y
  tests/jq.test
  tests/shtest
Labels: bug
