Repository jqlang/jq, pull requests merged in 2023-12, with the labels that each got.

#2963 jq_fuzz_execute.cpp: fix false assert
  tests/jq_fuzz_execute.cpp
Labels: bug, test

#2971 jq_fuzz_fixed: fix test cases that use string interpolation
  tests/jq_fuzz_fixed.cpp
Labels: bug, test

#2970 jv_setpath+setpath/2: don't leak the input after an invalid get
  src/jv_aux.c
  tests/jq.test
Labels: bug, libjq

#2898 chore: Improve readability (for Alternative operator '//')
  docs/content/manual/manual.yml
  jq.1.prebuilt
Labels: docs

#2980 shtest: fix out-of-source tests
  tests/shtest
Labels: bug, portability, test, lint

#2981 shtest+configure: remove uses of non-portable/non-standard commands
  configure.ac
  tests/shtest
Labels: portability, test

#2978 jv_mem_calloc(): always call with (nmemb, size)
  src/compile.c
  src/jv_aux.c
  src/jv_print.c
  src/locfile.c
Labels: lint

#2982 ci.yml: use `sysctl -n hw.logicalcpu` instead of `nproc` on macos
  .github/workflows/ci.yml
Labels: Github Actions

#2983 Makefile.am: don't use -lshlwapi to build jq on WIN32
  Makefile.am
Labels: build, windows, lint

#2977 ltrimstr/1+rtrimstr/1: don't leak on invalid input or arguments
  src/builtin.c
  tests/jq.test
Labels: bug, libjq

#2984 lexer: temporarily revert #\ patch; keep CR in comment bug fix
  docs/content/manual/manual.yml
  jq.1.prebuilt
  src/lexer.c
  src/lexer.h
  src/lexer.l
  src/main.c
  tests/shtest
Labels: release/packaging, libjq

#2948 Update NEWS.md with changes since 1.7
  NEWS.md
Labels: release/packaging, docs

#2985 jv_parse: let decNumberFromString/strtod parse complex nans as a NaN
  src/jv_parse.c
  tests/jq.test
Labels: bug, ieee754, libjq

#2997 Always build Docker image on CI, group Dependabot PRs for official actions
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: build
