Repository jqlang/jq, pull requests merged in 2023-11, with the labels that each got.

#2942 Comment bug fixes, and fully support Tcl-style multiline comments
  docs/content/manual/manual.yml
  jq.1.prebuilt
  src/lexer.c
  src/lexer.h
  src/lexer.l
  src/main.c
  tests/shtest
Labels: docs, feature request: jq function library

#2946 simplify paths/0 and paths/1
  src/builtin.jq
Labels: lint

#2953 libjq: extern C for C++
  src/jq.h
  src/jv.h
Labels: usability, libjq

#2951 Keep releasing executables with legacy names
  .github/workflows/ci.yml
Labels: release/packaging

#2955 website: use https URLs instead of http URLs in download page
  docs/content/download/default.yml
Labels: site

#2949 Convert decnum to binary64 (double) instead of decimal64
  src/jv.c
  tests/jq.test
Labels: ieee754, libjq
