Repository jqlang/jq, pull requests merged in 2023-08, with the labels that each got.

#2804 Fix rounding small (but not too small) numbers to zero on calculation (fix #2685)
  src/jv.c
  tests/jq.test
Labels: bug

#2818 Fix crash on numeric comparison (ref #2804)
  src/jv.c
  tests/jq.test
Labels: bug

#2824 Change the default color of null to Bright Black
  NEWS.md
  docs/content/manual/manual.yml
  jq.1.prebuilt
  src/jv_print.c
  tests/shtest
Labels: feature request

#2839 Fix crash on numeric comparison again (ref #2825)
  src/jv.c
  tests/jq.test
Labels: bug

#2842 Cast function pointers without prototype before calling them
  src/execute.c
Labels: build

#2817 Add --config option printing ./configure options used
  Makefile.am
  docs/content/manual/manual.yml
  jq.1.prebuilt
  src/main.c
Labels: feature request
