Repository jqlang/jq, pull requests merged in 2024-03, with the labels that each got.

#3069 EACH: fix leak when an error is triggered by non-last element of object
  src/execute.c
  tests/jq.test
Labels: bug

#3068 strftime/1: fix validation of non-string argument with number input
  src/builtin.c
  tests/jq.test
Labels: bug

#3071 util.c: fix _WIN32 port of strptime
  src/util.c
Labels: bug, external bug, windows

#3073 util.c: update strptime to revision 1.66
  src/util.c
Labels: dependencies

#3070 builtin.c: fix signed integer overflow in jv2tm
  src/builtin.c
  tests/jq.test
Labels: bug

#3056 Add trim/0, ltrim/0 and rtrim/0 that trims leading and trailing whitespace
  docs/content/manual/manual.yml
  jq.1.prebuilt
  src/builtin.c
  src/jv_unicode.c
  src/jv_unicode.h
  tests/jq.test
  tests/man.test
Labels: feature request

#3082 ci: Remove unnecessary apt-get upgrade
  .github/workflows/ci.yml
  .github/workflows/valgrind.yml
Labels: Github Actions

#3083 jv_setpath: fix leak when indexing an array with an array
  src/jv_aux.c
  tests/jq.test
Labels: bug
