Repository jqlang/jq, pull requests merged in 2024-08, with the labels that each got.

#3160 jv.h: define empty JV_{,V}PRINTF_LIKE macros if __GNUC__ is not defined
  src/jv.h
Labels: build, lint

#3162 mktime/0: remove unnecessary length>=6 input requirement
  src/builtin.c
  tests/jq.test
Labels: bug

#3114 source ~/.jq file on windows (fixes #3104)
  docs/content/manual/dev/manual.yml
  jq.1.prebuilt
  src/linker.c
  tests/shtest
Labels: windows
