Repository jqlang/jq, pull requests merged in 2025-02, with the labels that each got.

#3243 website: switch to custom domain jqlang.org
  README.md
  configure.ac
  docs/build_website.py
  docs/public/CNAME
  jq.spec
  libjq.pc.in
  src/main.c
Labels: site

#3212 build: fix insecure RUNPATH
  Makefile.am
Labels: build

#3232 Fix `--indent 0` implicitly enabling compact-output
  src/jv.h
  tests/shtest
Labels: bug

#3238 Non-matched optional capture group should be null and offset -1
  src/builtin.c
  tests/onig.test
Labels: bug

#3242 fix: preserve numerical precision on unary negation
  docs/content/manual/dev/manual.yml
  jq.1.prebuilt
  src/builtin.c
  src/jv.c
  src/jv.h
  tests/jq.test
  tests/man.test
Labels: bug

#3247 Add opengraph meta tags
  docs/templates/shared/_head.html.j2
Labels: site

#3248 website: remove unused root path on building website
  docs/README.md
  docs/build_website.py
  docs/content/download/default.yml
  docs/templates/index.html.j2
  docs/templates/manual.html.j2
  docs/templates/shared/_head.html.j2
  docs/templates/shared/_navbar.html.j2
Labels: site

#3245 fix: `jv_number_value` should cache the double value of literal numbers
  src/jv.c
Labels: performance

#3263 Fix compiler warning `type-limits` in `found_string` (ref #2911)
  src/jv_parse.c
  tests/shtest
Labels: lint

#3265 Replace jqplay.org with play.jqlang.org
  README.md
  docs/templates/index.html.j2
  docs/templates/manual.html.j2
  docs/templates/shared/_navbar.html.j2
Labels: site
