Repository jqlang/jq, pull requests merged in 2025-05, with the labels that each got.

#3255 Revert "Move closer to the standard autotools idiom. (#3187)"
  .gitignore
  Makefile.am
  configure.ac
  src/main.c
Labels: build

#3259 Fix warning: a function definition without a prototype is deprecated
  Makefile.am
  src/builtin.c
  src/compile.c
  src/compile.h
  src/jq_test.c
  src/jv.c
  src/jv_alloc.c
  src/jv_dtoa_tsd.c
  src/jv_dtoa_tsd.h
  src/main.c
  src/util.c
Labels: lint

#3261 Disable shared libraries on macOS to avoid conflict with -all-static
  .github/workflows/ci.yml
Labels: Github Actions

#3053 Fix unary operator precedence, allow some expressions as object values
  src/parser.c
  src/parser.y
  tests/jq.test
Labels: bug

#2098 Adds "toboolean" builtin function for converting strings to booleans
  docs/content/manual/dev/manual.yml
  jq.1.prebuilt
  src/builtin.c
  tests/jq.test
  tests/man.test
Labels: feature request

#3292 Improve error messages to show problematic position in the filter
  src/jq_test.c
  src/locfile.c
  src/parser.c
  src/parser.y
  tests/jq.test
  tests/shtest
Labels: feature request

#3325 Fix and refactor scan-build workflow to run on the master branch
  .github/workflows/scanbuild.yml
Labels: test

#3279 Fix behavior of `--slurp --stream` when input has no trailing newline character
  src/util.c
  tests/shtest
Labels: bug

#3326 Fix parser to allow binary operators for binding syntax
  src/parser.c
  src/parser.y
  tests/jq.test
Labels: bug

#3329 Fix quotes in 1.7 manual for ease of taking diff between versions
  docs/content/manual/v1.7/manual.yml
Labels: docs
