Repository jqlang/jq, pull requests merged in 2025-03, with the labels that each got.

#3254 improve performance of `unique` and `unique_by`
  src/builtin.c
  src/builtin.jq
  src/jv.h
  src/jv_aux.c
Labels: performance

#3278 Define `_BSD_SOURCE` in builtin.c for OpenBSD support
  src/builtin.c
  tests/optional.test
Labels: portability

#3274 Support CRLF line breaks in filters
  src/lexer.c
  src/lexer.h
  src/lexer.l
  tests/shtest
Labels: feature request

#3269 Disable Valgrind by default during testing
  .github/workflows/ci.yml
  .github/workflows/oniguruma.yml
  .github/workflows/scanbuild.yml
  .github/workflows/valgrind.yml
  Dockerfile
  Makefile.am
  configure.ac
  tests/setup
Labels: test

#3272 Improve performance of repeating strings
  src/builtin.c
  src/jv.c
  src/jv.h
  tests/jq.test
Labels: performance

#3271 Fix segmentation fault on `strftime/1` and `strflocaltime/1`
  src/builtin.c
Labels: bug

#3277 Enable z/OS support
  src/jq_test.c
Labels: portability

#3266 fix: `foreach` should not break init backtracking with `DUPN`
  src/compile.c
  tests/jq.test
Labels: bug

#3304 jv_unique: don't leak non-unique elements that are not returned
  src/jv_aux.c
Labels: bug
